name: Cypress Tests with Mochawesome Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npm run test

      - name: Generate Mochawesome Report
        run: npm run report:generate

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: mochawesome-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: mochawesome-report
